
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 09 11:56:11 CST 2024
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INDICE_MATRIZ = 23;
  public static final int CREAR = 3;
  public static final int REMOVER = 8;
  public static final int CORCHETEC = 22;
  public static final int PINTAR = 9;
  public static final int CORCHETEA = 21;
  public static final int MATRIZ = 20;
  public static final int ELIMINAR = 6;
  public static final int VACIAR = 11;
  public static final int ERROR = 25;
  public static final int COLOR = 15;
  public static final int ASIGNAR = 4;
  public static final int EOF = 0;
  public static final int MOSTRAR = 10;
  public static final int NUEVO_VALOR = 12;
  public static final int A = 16;
  public static final int FINAL = 24;
  public static final int error = 1;
  public static final int INDICE = 14;
  public static final int IDENTIFICADOR = 2;
  public static final int EN = 17;
  public static final int LISTA = 19;
  public static final int MODIFICAR = 5;
  public static final int AGREGAR = 7;
  public static final int ARRAY = 18;
  public static final int VALOR = 13;
}

