
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 08 03:51:52 CST 2024
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INDICE_MATRIZ = 24;
  public static final int CREAR = 4;
  public static final int REMOVER = 9;
  public static final int CORCHETEC = 23;
  public static final int PINTAR = 10;
  public static final int CORCHETEA = 22;
  public static final int MATRIZ = 21;
  public static final int ELIMINAR = 7;
  public static final int VACIAR = 12;
  public static final int ERROR = 26;
  public static final int COLOR = 16;
  public static final int ASIGNAR = 5;
  public static final int EOF = 0;
  public static final int MOSTRAR = 11;
  public static final int DIGITO = 13;
  public static final int A = 17;
  public static final int ULTIMO = 14;
  public static final int DE = 15;
  public static final int FINAL = 25;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 3;
  public static final int EN = 18;
  public static final int LISTA = 20;
  public static final int MODIFICAR = 6;
  public static final int ESPACIO = 2;
  public static final int AGREGAR = 8;
  public static final int ARRAY = 19;
}

